version: '3.8'

services:
  bot:
    build: .
    container_name: kufar_bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
